services:
  calendar-sync:
    build: .
    container_name: calendar-sync
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - SYNC_INTERVAL=900  # 15 minutes (in seconds)
      - LOG_LEVEL=INFO  # DEBUG, INFO, WARNING, ERROR
